/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Modele;

public class Cellule2 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Cellule2(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Cellule2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        texteJNI.delete_Cellule2(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setInode(int value) {
    texteJNI.Cellule2_inode_set(swigCPtr, value);
  }

  public int getInode() {
    return texteJNI.Cellule2_inode_get(swigCPtr);
  }

  public void setNboccu(int value) {
    texteJNI.Cellule2_nboccu_set(swigCPtr, value);
  }

  public int getNboccu() {
    return texteJNI.Cellule2_nboccu_get(swigCPtr);
  }

  public void setNom(String value) {
    texteJNI.Cellule2_nom_set(swigCPtr, value);
  }

  public String getNom() {
    return texteJNI.Cellule2_nom_get(swigCPtr);
  }

  public void setNext(SWIGTYPE_p_Cellule2 value) {
    texteJNI.Cellule2_next_set(swigCPtr, SWIGTYPE_p_Cellule2.getCPtr(value));
  }

  public SWIGTYPE_p_Cellule2 getNext() {
    long cPtr = texteJNI.Cellule2_next_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Cellule2(cPtr, false);
  }

  public Cellule2() {
    this(texteJNI.new_Cellule2(), true);
  }

}
