/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Modele;

public class Cellule {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Cellule(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Cellule obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        texteJNI.delete_Cellule(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMot(String value) {
    texteJNI.Cellule_mot_set(swigCPtr, value);
  }

  public String getMot() {
    return texteJNI.Cellule_mot_get(swigCPtr);
  }

  public void setTab(SWIGTYPE_p_a_2__int value) {
    texteJNI.Cellule_Tab_set(swigCPtr, SWIGTYPE_p_a_2__int.getCPtr(value));
  }

  public SWIGTYPE_p_a_2__int getTab() {
    long cPtr = texteJNI.Cellule_Tab_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_2__int(cPtr, false);
  }

  public void setNbref(int value) {
    texteJNI.Cellule_nbref_set(swigCPtr, value);
  }

  public int getNbref() {
    return texteJNI.Cellule_nbref_get(swigCPtr);
  }

  public void setNext(SWIGTYPE_p_Cellule value) {
    texteJNI.Cellule_next_set(swigCPtr, SWIGTYPE_p_Cellule.getCPtr(value));
  }

  public SWIGTYPE_p_Cellule getNext() {
    long cPtr = texteJNI.Cellule_next_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Cellule(cPtr, false);
  }

  public Cellule() {
    this(texteJNI.new_Cellule(), true);
  }

}
