/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Modele;

public class Cellule_Arbre_nb {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Cellule_Arbre_nb(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Cellule_Arbre_nb obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        image_nbJNI.delete_Cellule_Arbre_nb(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setGauche(Cellule_Arbre_nb value) {
    image_nbJNI.Cellule_Arbre_nb_gauche_set(swigCPtr, this, Cellule_Arbre_nb.getCPtr(value), value);
  }

  public Cellule_Arbre_nb getGauche() {
    long cPtr = image_nbJNI.Cellule_Arbre_nb_gauche_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Cellule_Arbre_nb(cPtr, false);
  }

  public void setValeur(float value) {
    image_nbJNI.Cellule_Arbre_nb_valeur_set(swigCPtr, this, value);
  }

  public float getValeur() {
    return image_nbJNI.Cellule_Arbre_nb_valeur_get(swigCPtr, this);
  }

  public void setNom(String value) {
    image_nbJNI.Cellule_Arbre_nb_nom_set(swigCPtr, this, value);
  }

  public String getNom() {
    return image_nbJNI.Cellule_Arbre_nb_nom_get(swigCPtr, this);
  }

  public void setDroite(Cellule_Arbre_nb value) {
    image_nbJNI.Cellule_Arbre_nb_droite_set(swigCPtr, this, Cellule_Arbre_nb.getCPtr(value), value);
  }

  public Cellule_Arbre_nb getDroite() {
    long cPtr = image_nbJNI.Cellule_Arbre_nb_droite_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Cellule_Arbre_nb(cPtr, false);
  }

  public Cellule_Arbre_nb() {
    this(image_nbJNI.new_Cellule_Arbre_nb(), true);
  }

}
