/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Modele;

public class Cellule_File_nb {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Cellule_File_nb(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Cellule_File_nb obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        image_nbJNI.delete_Cellule_File_nb(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDesc_inode(String value) {
    image_nbJNI.Cellule_File_nb_desc_inode_set(swigCPtr, this, value);
  }

  public String getDesc_inode() {
    return image_nbJNI.Cellule_File_nb_desc_inode_get(swigCPtr, this);
  }

  public void setDesc_histo(nb_occ value) {
    image_nbJNI.Cellule_File_nb_desc_histo_set(swigCPtr, this, nb_occ.getCPtr(value), value);
  }

  public nb_occ getDesc_histo() {
    long cPtr = image_nbJNI.Cellule_File_nb_desc_histo_get(swigCPtr, this);
    return (cPtr == 0) ? null : new nb_occ(cPtr, false);
  }

  public void setDesc_total(int value) {
    image_nbJNI.Cellule_File_nb_desc_total_set(swigCPtr, this, value);
  }

  public int getDesc_total() {
    return image_nbJNI.Cellule_File_nb_desc_total_get(swigCPtr, this);
  }

  public void setSuivant(Cellule_File_nb value) {
    image_nbJNI.Cellule_File_nb_suivant_set(swigCPtr, this, Cellule_File_nb.getCPtr(value), value);
  }

  public Cellule_File_nb getSuivant() {
    long cPtr = image_nbJNI.Cellule_File_nb_suivant_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Cellule_File_nb(cPtr, false);
  }

  public Cellule_File_nb() {
    this(image_nbJNI.new_Cellule_File_nb(), true);
  }

}
