/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Modele;

public class communJNI {
  public final static native void Config_num_set(long jarg1, String jarg2);
  public final static native String Config_num_get(long jarg1);
  public final static native long new_Config();
  public final static native void delete_Config(long jarg1);
  public final static native int file_exists(String jarg1, String jarg2, String jarg3);
  public final static native int fileExists(String jarg1);
  public final static native void init_config(long jarg1);
  public final static native String init_path();
  public final static native String get_password();
  public final static native String get_config_texte();
  public final static native void edit_path(String jarg1);
  public final static native void new_password(String jarg1);
  public final static native String config(int jarg1);
  public final static native void encrypt2(String jarg1);
  public final static native void decrypt(String jarg1);
  public final static native void edit_settings_text(int jarg1, int jarg2, int jarg3);
  public final static native void edit_settings_image(int jarg1, int jarg2);
  public final static native void edit_settings_sound(int jarg1, int jarg2);
  public final static native void test_setup();
  public final static native String get_config_image();
  public final static native String get_config_son();
  public final static native String get_path();
}
