/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Modele;

public class File_nb {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected File_nb(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(File_nb obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        image_nbJNI.delete_File_nb(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTete(Cellule_File_nb value) {
    image_nbJNI.File_nb_tete_set(swigCPtr, this, Cellule_File_nb.getCPtr(value), value);
  }

  public Cellule_File_nb getTete() {
    long cPtr = image_nbJNI.File_nb_tete_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Cellule_File_nb(cPtr, false);
  }

  public void setQueue(Cellule_File_nb value) {
    image_nbJNI.File_nb_queue_set(swigCPtr, this, Cellule_File_nb.getCPtr(value), value);
  }

  public Cellule_File_nb getQueue() {
    long cPtr = image_nbJNI.File_nb_queue_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Cellule_File_nb(cPtr, false);
  }

  public File_nb() {
    this(image_nbJNI.new_File_nb(), true);
  }

}
