/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Modele;

public class File {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected File(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(File obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        texteJNI.delete_File(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTete(SWIGTYPE_p_Cellule2 value) {
    texteJNI.File_tete_set(swigCPtr, SWIGTYPE_p_Cellule2.getCPtr(value));
  }

  public SWIGTYPE_p_Cellule2 getTete() {
    long cPtr = texteJNI.File_tete_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Cellule2(cPtr, false);
  }

  public void setQueue(SWIGTYPE_p_Cellule2 value) {
    texteJNI.File_queue_set(swigCPtr, SWIGTYPE_p_Cellule2.getCPtr(value));
  }

  public SWIGTYPE_p_Cellule2 getQueue() {
    long cPtr = texteJNI.File_queue_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Cellule2(cPtr, false);
  }

  public File() {
    this(texteJNI.new_File(), true);
  }

}
