/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Modele;

public class HISTO {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected HISTO(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(HISTO obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        image_nbJNI.delete_HISTO(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setValeur(int value) {
    image_nbJNI.HISTO_valeur_set(swigCPtr, this, value);
  }

  public int getValeur() {
    return image_nbJNI.HISTO_valeur_get(swigCPtr, this);
  }

  public void setOccurence(int value) {
    image_nbJNI.HISTO_occurence_set(swigCPtr, this, value);
  }

  public int getOccurence() {
    return image_nbJNI.HISTO_occurence_get(swigCPtr, this);
  }

  public HISTO() {
    this(image_nbJNI.new_HISTO(), true);
  }

}
