/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Modele;

public class image_nbJNI {
  public final static native void nb_occ_nb_set(long jarg1, nb_occ jarg1_, int jarg2);
  public final static native int nb_occ_nb_get(long jarg1, nb_occ jarg1_);
  public final static native void nb_occ_occ_set(long jarg1, nb_occ jarg1_, int jarg2);
  public final static native int nb_occ_occ_get(long jarg1, nb_occ jarg1_);
  public final static native long new_nb_occ();
  public final static native void delete_nb_occ(long jarg1);
  public final static native void Cellule_File_nb_desc_inode_set(long jarg1, Cellule_File_nb jarg1_, String jarg2);
  public final static native String Cellule_File_nb_desc_inode_get(long jarg1, Cellule_File_nb jarg1_);
  public final static native void Cellule_File_nb_desc_histo_set(long jarg1, Cellule_File_nb jarg1_, long jarg2, nb_occ jarg2_);
  public final static native long Cellule_File_nb_desc_histo_get(long jarg1, Cellule_File_nb jarg1_);
  public final static native void Cellule_File_nb_desc_total_set(long jarg1, Cellule_File_nb jarg1_, int jarg2);
  public final static native int Cellule_File_nb_desc_total_get(long jarg1, Cellule_File_nb jarg1_);
  public final static native void Cellule_File_nb_suivant_set(long jarg1, Cellule_File_nb jarg1_, long jarg2, Cellule_File_nb jarg2_);
  public final static native long Cellule_File_nb_suivant_get(long jarg1, Cellule_File_nb jarg1_);
  public final static native long new_Cellule_File_nb();
  public final static native void delete_Cellule_File_nb(long jarg1);
  public final static native void File_nb_tete_set(long jarg1, File_nb jarg1_, long jarg2, Cellule_File_nb jarg2_);
  public final static native long File_nb_tete_get(long jarg1, File_nb jarg1_);
  public final static native void File_nb_queue_set(long jarg1, File_nb jarg1_, long jarg2, Cellule_File_nb jarg2_);
  public final static native long File_nb_queue_get(long jarg1, File_nb jarg1_);
  public final static native long new_File_nb();
  public final static native void delete_File_nb(long jarg1);
  public final static native void init_file(long jarg1, File_nb jarg1_);
  public final static native int file_est_vide(long jarg1, File_nb jarg1_);
  public final static native void enfiler(long jarg1, File_nb jarg1_, String jarg2, long jarg3, nb_occ jarg3_, int jarg4);
  public final static native void defiler(long jarg1, File_nb jarg1_, String jarg2, long jarg3, nb_occ jarg3_);
  public final static native void affiche_file(long jarg1, File_nb jarg1_);
  public final static native void Cellule_Arbre_nb_gauche_set(long jarg1, Cellule_Arbre_nb jarg1_, long jarg2, Cellule_Arbre_nb jarg2_);
  public final static native long Cellule_Arbre_nb_gauche_get(long jarg1, Cellule_Arbre_nb jarg1_);
  public final static native void Cellule_Arbre_nb_valeur_set(long jarg1, Cellule_Arbre_nb jarg1_, float jarg2);
  public final static native float Cellule_Arbre_nb_valeur_get(long jarg1, Cellule_Arbre_nb jarg1_);
  public final static native void Cellule_Arbre_nb_nom_set(long jarg1, Cellule_Arbre_nb jarg1_, String jarg2);
  public final static native String Cellule_Arbre_nb_nom_get(long jarg1, Cellule_Arbre_nb jarg1_);
  public final static native void Cellule_Arbre_nb_droite_set(long jarg1, Cellule_Arbre_nb jarg1_, long jarg2, Cellule_Arbre_nb jarg2_);
  public final static native long Cellule_Arbre_nb_droite_get(long jarg1, Cellule_Arbre_nb jarg1_);
  public final static native long new_Cellule_Arbre_nb();
  public final static native void delete_Cellule_Arbre_nb(long jarg1);
  public final static native void init_Arbre_nb(long jarg1);
  public final static native void affiche_Arbre_nb(long jarg1, Cellule_Arbre_nb jarg1_, String jarg2);
  public final static native int Arbre_nb_vide(long jarg1, Cellule_Arbre_nb jarg1_);
  public final static native long ajout_ds_Arbre_nb_croissant(long jarg1, Cellule_Arbre_nb jarg1_, float jarg2, String jarg3);
  public final static native long ajout_ds_Arbre_nb_decroissant(long jarg1, Cellule_Arbre_nb jarg1_, float jarg2, String jarg3);
  public final static native long ajout_si_vide(float jarg1, String jarg2);
  public final static native void enlever_max_de_Arbre_nb(long jarg1, long jarg2);
  public final static native void recup_max_arbre(long jarg1, Cellule_Arbre_nb jarg1_, String jarg2);
  public final static native String affiche_res_niveau(long jarg1, Cellule_Arbre_nb jarg1_, int jarg2);
  public final static native float calcul_pourcentage(int jarg1, int jarg2);
  public final static native void recup_nom_fic_a_indexer(String jarg1);
  public final static native void get_inode_fichier_encours(String jarg1, String jarg2);
  public final static native void ecrire_liste_base_image_nb(String jarg1, String jarg2);
  public final static native void enlever_entree(String jarg1);
  public final static native void indexation_une_image(String jarg1, String jarg2, long jarg3, nb_occ jarg3_, long jarg4);
  public final static native void indexation_image_nb();
  public final static native void recup_nom_fic_via_inode(String jarg1, String jarg2);
  public final static native String txt_to_bmp(String jarg1);
  public final static native String bmp_to_txt(String jarg1);
  public final static native String affiche_res_similarite(long jarg1, Cellule_Arbre_nb jarg1_);
  public final static native int verif_format(String jarg1);
  public final static native String recherche_similarite_image_nb(String jarg1);
  public final static native void image_panel();
  public final static native String recherche_niveau_image_nb(int jarg1);
  public final static native int verif_intervalle(int jarg1);
  public final static native void HISTO_valeur_set(long jarg1, HISTO jarg1_, int jarg2);
  public final static native int HISTO_valeur_get(long jarg1, HISTO jarg1_);
  public final static native void HISTO_occurence_set(long jarg1, HISTO jarg1_, int jarg2);
  public final static native int HISTO_occurence_get(long jarg1, HISTO jarg1_);
  public final static native long new_HISTO();
  public final static native void delete_HISTO(long jarg1);
  public final static native void fic_descripteurs(String jarg1, String jarg2);
  public final static native void fic_liste_desc(String jarg1, String jarg2);
  public final static native void open_image_c();
  public final static native void quantification_im_c(long jarg1, int jarg2, int jarg3, int jarg4, int jarg5, String jarg6);
  public final static native int threeToOne(int jarg1, int jarg2, int jarg3, int jarg4);
  public final static native void decompo_binaire(long jarg1, int jarg2, int jarg3);
  public final static native int binaryToDeci(long jarg1);
  public final static native void histogramme(long jarg1, int jarg2, int jarg3, String jarg4);
  public final static native void Cellule_Arbre_c_gauche_set(long jarg1, Cellule_Arbre_c jarg1_, long jarg2, Cellule_Arbre_c jarg2_);
  public final static native long Cellule_Arbre_c_gauche_get(long jarg1, Cellule_Arbre_c jarg1_);
  public final static native void Cellule_Arbre_c_valeur_set(long jarg1, Cellule_Arbre_c jarg1_, float jarg2);
  public final static native float Cellule_Arbre_c_valeur_get(long jarg1, Cellule_Arbre_c jarg1_);
  public final static native void Cellule_Arbre_c_nom_set(long jarg1, Cellule_Arbre_c jarg1_, String jarg2);
  public final static native String Cellule_Arbre_c_nom_get(long jarg1, Cellule_Arbre_c jarg1_);
  public final static native void Cellule_Arbre_c_droite_set(long jarg1, Cellule_Arbre_c jarg1_, long jarg2, Cellule_Arbre_c jarg2_);
  public final static native long Cellule_Arbre_c_droite_get(long jarg1, Cellule_Arbre_c jarg1_);
  public final static native long new_Cellule_Arbre_c();
  public final static native void delete_Cellule_Arbre_c(long jarg1);
  public final static native void init_Arbre_c(long jarg1);
  public final static native void affiche_Arbre_c(long jarg1, Cellule_Arbre_c jarg1_, String jarg2);
  public final static native int Arbre_c_vide(long jarg1, Cellule_Arbre_c jarg1_);
  public final static native long ajout_ds_Arbre_c_croissant(long jarg1, Cellule_Arbre_c jarg1_, float jarg2, String jarg3);
  public final static native long ajout_ds_Arbre_c_decroissant(long jarg1, Cellule_Arbre_c jarg1_, float jarg2, String jarg3);
  public final static native long ajout_si_vide_c(float jarg1, String jarg2);
  public final static native void enlever_max_de_Arbre_c(long jarg1, long jarg2);
  public final static native void recup_max_arbre_c(long jarg1, Cellule_Arbre_c jarg1_, String jarg2);
  public final static native String affiche_res_similarite_rgb(long jarg1, Cellule_Arbre_c jarg1_);
  public final static native int verif_format_rgb(String jarg1);
  public final static native void recup_nom_fic_via_inode_rgb(String jarg1, String jarg2);
  public final static native String jpg_to_txt(String jarg1);
  public final static native String txt_to_jpg(String jarg1);
  public final static native String recherche_similarite_image_couleurs(String jarg1);
  public final static native void indexation_une_image_rgb(String jarg1, String jarg2, long jarg3, HISTO jarg3_, long jarg4, long jarg5);
  public final static native float similarite_fics(long jarg1, HISTO jarg1_, long jarg2, long jarg3, long jarg4);
}
