/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Modele;

public class nb_occ {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected nb_occ(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(nb_occ obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        image_nbJNI.delete_nb_occ(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNb(int value) {
    image_nbJNI.nb_occ_nb_set(swigCPtr, this, value);
  }

  public int getNb() {
    return image_nbJNI.nb_occ_nb_get(swigCPtr, this);
  }

  public void setOcc(int value) {
    image_nbJNI.nb_occ_occ_set(swigCPtr, this, value);
  }

  public int getOcc() {
    return image_nbJNI.nb_occ_occ_get(swigCPtr, this);
  }

  public nb_occ() {
    this(image_nbJNI.new_nb_occ(), true);
  }

}
