/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Modele;

public class son {
  public static void indexationSon(String FICHIER) {
    sonJNI.indexationSon(FICHIER);
  }

  public static void indexSon() {
    sonJNI.indexSon();
  }

  public static int existSon(String inode) {
    return sonJNI.existSon(inode);
  }

  public static String rechercheSonBis(String c) {
    return sonJNI.rechercheSonBis(c);
  }

  public static void premiereValeur1() {
    sonJNI.premiereValeur1();
  }

  public static void premiereValeur2() {
    sonJNI.premiereValeur2();
  }

  public static void distance(int arg0) {
    sonJNI.distance(arg0);
  }

  public static void valeurSuivante() {
    sonJNI.valeurSuivante();
  }

  public static int compareSon() {
    return sonJNI.compareSon();
  }

  public static void rechercheSon() {
    sonJNI.rechercheSon();
  }

}
