/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Modele;

public class sonJNI {
  public final static native void indexationSon(String jarg1);
  public final static native void indexSon();
  public final static native int existSon(String jarg1);
  public final static native void premiereValeur1();
  public final static native void premiereValeur2();
  public final static native void distance(int jarg1);
  public final static native void valeurSuivante();
  public final static native int compareSon();
  public final static native void rechercheSon();
}
