/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Modele;

public class Terme {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Terme(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Terme obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        texteJNI.delete_Terme(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMot(String value) {
    texteJNI.Terme_mot_set(swigCPtr, value);
  }

  public String getMot() {
    return texteJNI.Terme_mot_get(swigCPtr);
  }

  public void setNb_occu(int value) {
    texteJNI.Terme_nb_occu_set(swigCPtr, value);
  }

  public int getNb_occu() {
    return texteJNI.Terme_nb_occu_get(swigCPtr);
  }

  public Terme() {
    this(texteJNI.new_Terme(), true);
  }

}
