/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Modele;

public class texteJNI {
  public final static native int Taille_Max_get();
  public final static native void Terme_mot_set(long jarg1, String jarg2);
  public final static native String Terme_mot_get(long jarg1);
  public final static native void Terme_nb_occu_set(long jarg1, int jarg2);
  public final static native int Terme_nb_occu_get(long jarg1);
  public final static native long new_Terme();
  public final static native void delete_Terme(long jarg1);
  public final static native void ignore_balise(String jarg1);
  public final static native void ignore_commas(String jarg1);
  public final static native void traitement_file(String jarg1);
  public final static native void Cellule_mot_set(long jarg1, String jarg2);
  public final static native String Cellule_mot_get(long jarg1);
  public final static native void Cellule_Tab_set(long jarg1, long jarg2);
  public final static native long Cellule_Tab_get(long jarg1);
  public final static native void Cellule_nbref_set(long jarg1, int jarg2);
  public final static native int Cellule_nbref_get(long jarg1);
  public final static native void Cellule_next_set(long jarg1, long jarg2);
  public final static native long Cellule_next_get(long jarg1);
  public final static native long new_Cellule();
  public final static native void delete_Cellule(long jarg1);
  public final static native long init_PILE();
  public final static native int PILE_estVide(long jarg1);
  public final static native long emPILE(long jarg1, String jarg2, int jarg3, int jarg4);
  public final static native void ignore_etoile(String jarg1);
  public final static native void Result_nom_set(long jarg1, String jarg2);
  public final static native String Result_nom_get(long jarg1);
  public final static native void Result_match_set(long jarg1, float jarg2);
  public final static native float Result_match_get(long jarg1);
  public final static native long new_Result();
  public final static native void delete_Result(long jarg1);
  public final static native void indexer();
  public final static native String recherchecrit(String jarg1);
  public final static native String recherchesimi(String jarg1);
  public final static native int pathFileExists(String jarg1);
  public final static native void Cellule2_inode_set(long jarg1, int jarg2);
  public final static native int Cellule2_inode_get(long jarg1);
  public final static native void Cellule2_nboccu_set(long jarg1, int jarg2);
  public final static native int Cellule2_nboccu_get(long jarg1);
  public final static native void Cellule2_nom_set(long jarg1, String jarg2);
  public final static native String Cellule2_nom_get(long jarg1);
  public final static native void Cellule2_next_set(long jarg1, long jarg2);
  public final static native long Cellule2_next_get(long jarg1);
  public final static native long new_Cellule2();
  public final static native void delete_Cellule2(long jarg1);
  public final static native void File_tete_set(long jarg1, long jarg2);
  public final static native long File_tete_get(long jarg1);
  public final static native void File_queue_set(long jarg1, long jarg2);
  public final static native long File_queue_get(long jarg1);
  public final static native long new_File();
  public final static native void delete_File(long jarg1);
  public final static native long init_FILE(long jarg1);
  public final static native String affiche_FILE(long jarg1);
  public final static native int est_Vide_FILE(long jarg1);
  public final static native long enfiler_FILE(int jarg1, int jarg2, long jarg3);
  public final static native void notempty1_set(long jarg1);
  public final static native long notempty1_get();
  public final static native void notempty2_set(long jarg1);
  public final static native long notempty2_get();
}
